### ISSUE TITLE
Additional logic

### ISSUE THREAD

**Issue by deathbybandaid** [fabricionaweb/sonarr-tba-rename#1]
I really like your script, "does what it says on the tin".

I do though have some ideas for some logic to be added to it.
I've noticed I have may series that legitimately have episode titles of "Episode 1", "Episode 2".

I think that the regex search for "Episode" titles should be split from the regex search for "TBA" with some configuration option.
I think there should be some sort of csv "flat database" to compare and contrast things that the script has previously had sonarr attempt to refresh, but has been attempted X variable times.
It may also be beneficial to be able to skip files prior to a configurable amount of time. Such as past the last month/year.

**Comment by fabricionaweb** [comment]
Thanks for the feedback! It have been a while since I touch the script, its just running sit there 😅 I dont even check the output hehe

To be honest theres some stuff that I want to remove, make it cleaner, bash is a tricky language, but anyways.

> I've noticed I have may series that legitimately have episode titles of "Episode 1", "Episode 2".

Yes me too, I have three, one serie is ended but two others is airing, while I think some of them later can get titles from TVDB, I know the other would also never...

I dont want to bloat the script too much, but what do you think about an "oldest than" date? If the episode is older than X days, we skip it no matter what...

(not sure) but I think it doable

**Comment by deathbybandaid** [comment]
I think most users of the script would likely do a manual run at least once, and then set a cron job.

So I'd run it against my sonarr once with no limits, then I'd set a cron for maybe 30 days.

Maybe the script could take arguments. This way you could set a daily cron that covers the last 30 days, and another cron that does something else.

Also, it would probably be beneficial to source variables from another file that doesn't get wiped out on a git pull. (potential future script updates)

**Comment by fabricionaweb** [comment]
I have added a new config `FILTER_DAYS="14"` that is how many days you want filter out.

Using 14 days would mean if the episode air date is older than that, It probably wont be getting any title or "Episode X" is definitive 😅 

But also it can reading the value from env, as suggested, so you could use it like you said:

```
FILTER_DAYS=30 ./tba-rename.sh
```

I honest dont want to be adding too much logic or options, I hope that helps us already.
Thanks for the suggestions!
